linkedItems[]=
{
	"17TH_M52A_Autorifleman",
	"ItemMap",
	"ItemCompass",
	"ACE_Altimeter",
	"ItemRadio",
	"OPTRE_Smartfinder",
	"ItemGPS"
};
respawnLinkedItems[]=
{
	"17TH_M52A_Autorifleman",
	"ItemMap",
	"ItemCompass",
	"ACE_Altimeter",
	"ItemRadio",
	"OPTRE_Smartfinder",
	"ItemGPS"
};