linkedItems[]=
{
	"OPTRE_Ins_URF_Armor1",
	"ItemMap",
	"ItemCompass",
	"ACE_Altimeter",
	"ItemRadio",
	"OPTRE_Smartfinder",
	"ItemGPS"
};
respawnLinkedItems[]=
{
	"OPTRE_Ins_URF_Armor1",
	"ItemMap",
	"ItemCompass",
	"ACE_Altimeter",
	"ItemRadio",
	"OPTRE_Smartfinder",
	"ItemGPS"
};